export enum TermeditorClicks {
  TERM_SELECTED_DOWNWARDS,
  TERM_SELECTED_UPWARDS,
  TERM_EDITED,
  TERM_RELATIONSHIP_REMOVED,
  TERM_RELATIONSHIP_ADDED,
  NEW_TERM,
  TERM_DELETED,
  BACK_TO_PREVIOUS,
  LIST_SELECTION
}
